FROM python:3.11-slim

# Working directory inside container
WORKDIR /app

# Copy dependency files first for caching
#RUN pip install --upgrade pip && pip install uv

COPY pyproject.toml uv.lock .app//ui_util/
COPY pyproject.toml uv.lock .app//handler/
COPY pyproject.toml uv.lock .app/cv2/
#RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your main app
COPY . .

# Optional: expose port if needed
#EXPOSE 8000

#CMD ["python", "main2.py"]
