# Base image
FROM python:3.11

COPY --from=ghcr.io/astral-sh/uv:0.5.22 /uv /uvx /bin/

ADD . /app/ui

# Set working directory
WORKDIR /app/ui


# Copy dependency files first (for caching)
COPY pyproject.toml uv.lock ./

RUN uv sync --locked

# Copy service code
COPY . .

# Expose port if needed
EXPOSE 5002

# Default command
#CMD ["python3", "overlay_test7.py"]
CMD ["uv","run","uvicorn","main:app","--host","127.0.0.1","--port","5002"]
