# Base image
FROM python:3.11

# getting uv 
COPY --from=ghcr.io/astral-sh/uv:0.5.22 /uv /uvx /bin/

ADD . /app/cv_server

# Set working directory
WORKDIR /app/cv_server




# Copy dependency files first (for caching)
COPY pyproject.toml uv.lock ./

RUN uv sync --locked

# Copy service code
COPY . .

# Expose port if needed
EXPOSE 5001

# Default command
#CMD ["python3", "server_cv.py"]
CMD ["uv","run","uvicorn","main:app","--host","127.0.0.1","--port","5001"]
